<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@3.0.1 cherry_tree.glb --transform
Author: local.yany (https://sketchfab.com/local.yany)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/cherry-tree-5f6d9059b971429999343e0f398bf487
Title: Cherry Tree
-->

<script lang="ts">
	import { T } from '@threlte/core';
	// 1. Import useDraco along with useGltf
	import { useGltf, useDraco } from '@threlte/extras';
	import type { Snippet } from 'svelte';

	let {
		fallback,
		error,
		children,
		ref = $bindable(),
		...props
	} = $props<
		{
			fallback?: Snippet;
			error?: Snippet;
			children?: Snippet;
		} & Record<string, any>
	>();

	const modelUrl = '/models/cherry_tree-transformed.glb';

	const dracoLoader = useDraco('https://www.gstatic.com/draco/versioned/decoders/1.5.7/');

	const gltf = useGltf(modelUrl, {
		dracoLoader
	});
</script>

<T.Group bind:ref dispose={false} {...props}>
	{#await gltf}
		{@render fallback?.()}
	{:then gltf}
		<T.Group scale={0.026} position={[0, -4, 0]}>
			<T.Group rotation={[0, 1.2, 0]}>
				<T.Mesh
					geometry={gltf.nodes.v176PebblesPetalsLeavesShape_v176PebblesPetalsLeaves_0.geometry}
					material={gltf.materials.v176PebblesPetalsLeaves}
					position={[0.93, 0.01, 1.74]}
					rotation={[0, -0.83, 0]}
					scale={1.6}
				/>
				<T.Mesh
					geometry={gltf.nodes.v176PebblesPetalsLeaves_dup_2Shape_v176PebblesPetalsLeaves_0
						.geometry}
					material={gltf.materials.v176PebblesPetalsLeaves_0}
					position={[0.93, 0.01, 1.74]}
					rotation={[-Math.PI, -1.5, -Math.PI]}
					scale={1.04}
				/>
				<T.Mesh
					geometry={gltf.nodes.flying_petalsShape_v176CherryPetal_0.geometry}
					material={gltf.materials.v176CherryPetal}
					position={[-9.6, 0, -144.46]}
					rotation={[-Math.PI, -1.44, -Math.PI]}
				/>
				<T.Mesh
					geometry={gltf.nodes.v176CherryTree02Shape_v176FCT_Rock_0.geometry}
					material={gltf.materials.v176FCT_Rock}
				/>
				<T.Mesh
					geometry={gltf.nodes.v176CherryTree02Shape_v176CherryBark01_0.geometry}
					material={gltf.materials.v176CherryBark01}
				/>
				<T.Mesh
					geometry={gltf.nodes.v176CherryTree02Shape_v176CherryBranch01_0.geometry}
					material={gltf.materials.v176CherryBranch01}
				/>
				<T.Mesh
					geometry={gltf.nodes.v176CherryTree02Shape_v176CherryBranch01_0_1.geometry}
					material={gltf.materials.v176CherryBranch01}
				/>
				<T.Mesh
					geometry={gltf.nodes.v176CherryTree02Shape_v176CherryBranch01_0_2.geometry}
					material={gltf.materials.v176CherryBranch01}
				/>
				<T.Mesh
					geometry={gltf.nodes.v176CherryTree02Shape_v176CherryFlowerStalk_0.geometry}
					material={gltf.materials.v176CherryFlowerStalk}
				/>
				<T.Mesh
					geometry={gltf.nodes.v176CherryTree02Shape_v176CherryFlowerStalk_0_1.geometry}
					material={gltf.materials.v176CherryFlowerStalk}
				/>
				<T.Mesh
					geometry={gltf.nodes.v176CherryTree02Shape_v176CherryFlowerStalk_0_2.geometry}
					material={gltf.materials.v176CherryFlowerStalk}
				/>
				<T.Mesh
					geometry={gltf.nodes.v176CherryTree02Shape_v176CherryFlowerStalk_0_3.geometry}
					material={gltf.materials.v176CherryFlowerStalk}
				/>
				<T.Mesh
					geometry={gltf.nodes.v176CherryTree02Shape_v176CherryFlowerStalk_0_4.geometry}
					material={gltf.materials.v176CherryFlowerStalk}
				/>
				<T.Mesh
					geometry={gltf.nodes.v176CherryTree02Shape_v176CherryFlowerStalk_0_5.geometry}
					material={gltf.materials.v176CherryFlowerStalk}
				/>
				<T.Mesh
					geometry={gltf.nodes.v176CherryTree02Shape_v176CherryFlowerStalk_0_6.geometry}
					material={gltf.materials.v176CherryFlowerStalk}
				/>
				<T.Mesh
					geometry={gltf.nodes.v176CherryTree02Shape_v176CherryFlowerStalk_0_7.geometry}
					material={gltf.materials.v176CherryFlowerStalk}
				/>
				<T.Mesh
					geometry={gltf.nodes.v176CherryTree02Shape_v176CherryFlowerStalk_0_8.geometry}
					material={gltf.materials.v176CherryFlowerStalk}
				/>
				<T.Mesh
					geometry={gltf.nodes.v176CherryTree02Shape_v176CherryFlowerStalk_0_9.geometry}
					material={gltf.materials.v176CherryFlowerStalk}
				/>
				<T.Mesh
					geometry={gltf.nodes.v176CherryTree02Shape_v176CherryFlowerStalk_0_10.geometry}
					material={gltf.materials.v176CherryFlowerStalk}
				/>
				<T.Mesh
					geometry={gltf.nodes.v176CherryTree02Shape_v176CherryFlowerStalk_0_11.geometry}
					material={gltf.materials.v176CherryFlowerStalk}
				/>
				<T.Mesh
					geometry={gltf.nodes.v176CherryTree02Shape_v176CherryFlowerStalk_0_12.geometry}
					material={gltf.materials.v176CherryFlowerStalk}
				/>
				<T.Mesh
					geometry={gltf.nodes.v176CherryTree02Shape_v176CherryFlowerStalk_0_13.geometry}
					material={gltf.materials.v176CherryFlowerStalk}
				/>
				<T.Mesh
					geometry={gltf.nodes.v176CherryTree02Shape_v176CherryFlowerStalk_0_14.geometry}
					material={gltf.materials.v176CherryFlowerStalk}
				/>
				<T.Mesh
					geometry={gltf.nodes.v176CherryTree02Shape_v176CherryFlowerStalk_0_15.geometry}
					material={gltf.materials.v176CherryFlowerStalk}
				/>
				<T.Mesh
					geometry={gltf.nodes.v176CherryTree02Shape_v176CherryFlowerStalk_0_16.geometry}
					material={gltf.materials.v176CherryFlowerStalk}
				/>
				<T.Mesh
					geometry={gltf.nodes.v176CherryTree02Shape_v176CherryFlowerStalk_0_17.geometry}
					material={gltf.materials.v176CherryFlowerStalk}
				/>
				<T.Mesh
					geometry={gltf.nodes.v176CherryTree02Shape_v176CherryFlowerStalk_0_18.geometry}
					material={gltf.materials.v176CherryFlowerStalk}
				/>
				<T.Mesh
					geometry={gltf.nodes.v176CherryTree02Shape_v176CherryBud_0.geometry}
					material={gltf.materials.v176CherryBud}
				/>
				<T.Mesh
					geometry={gltf.nodes.v176CherryTree02Shape_v176CherryBud_0_1.geometry}
					material={gltf.materials.v176CherryBud}
				/>
				<T.Mesh
					geometry={gltf.nodes.v176CherryTree02Shape_v176CherryBud_0_2.geometry}
					material={gltf.materials.v176CherryBud}
				/>
				<T.Mesh
					geometry={gltf.nodes.v176CherryTree02Shape_v176Tree_Knot_0.geometry}
					material={gltf.materials.v176Tree_Knot}
				/>
				<T.Mesh
					geometry={gltf.nodes.v176CherryTree02Shape_v176CherryFlower_0.geometry}
					material={gltf.materials.v176CherryFlower}
				/>
				<T.Mesh
					geometry={gltf.nodes.v176CherryTree02Shape_v176CherryFlower_0_1.geometry}
					material={gltf.materials.v176CherryFlower}
				/>
			</T.Group>
		</T.Group>
	{:catch err}
		{@render error?.({ error: err })}
	{/await}

	{@render children?.({ ref })}
</T.Group>
